name: Keepalive
on:
    schedule:
        - cron: "0 0 1 * *"

jobs:
    keepalive:
        name: Cronjob based github action
        runs-on: ubuntu-latest
        steps:
            - uses: gautamkrishnar/keepalive-workflow@v1
