name: Generate Metrics
on:
  push:
  schedule:
  - cron: "0 0 * * 0"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate terminal metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: terminal-metrics.svg
          committer_message: Update metrics (${filename})
          template: "@windows-terminal"
          config_padding: 6%, 20%
          setup_community_templates: Encode42/Encode42@metrics-template:windows-terminal+trust
          base: header, activity, repositories
          config_timezone: America/New_York
          config_animations: no
          verify: yes
          repositories_forks: yes
          plugin_followup: yes

      - name: Generate standard metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: standard-metrics.svg
          committer_message: Update metrics (${filename})
          template: classic
          base: ""
          config_timezone: America/New_York
          config_animations: no
          verify: yes
          repositories_forks: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 31
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 5
          plugin_languages_threshold: 0%